# apiVersion: v1
# kind: Service
# metadata:
#   name: static-ip
#   namespace: openfaas-fn
#   labels:
#     app: chain-1
# spec:
#   selector:
#     matchLabels:
#       app: chain-1
#     annotations:
#       ovn.kubernetes.io/ip_address: 10.10.10.10

apiVersion: v1
kind: Service
metadata:
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    prometheus.io.scrape: 'false'
    ovn.kubernetes.io/vip: vip-dynamic-01
  name: chain-1
  namespace: openfaas-fn
  resourceVersion: '244084'
spec:
  clusterIP: 10.16.0.34
  clusterIPs:
    - 10.16.0.34
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    faas_function: chain-1
  sessionAffinity: None
  type: ClusterIP



