apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet-svc
spec:
  protocol: IPv4
  cidrBlock: 10.64.0.0/12
  default: false
  excludeIps:
  - 10.64.0.1
  gateway: 10.64.0.1
  gatewayType: distributed
  natOutgoing: true
  namespaces: 
  - ns2
